language: python
python:
  - "3.6"

install:
  - pip install -r requirements.txt

service:
  - postgresql

before_script:
  - createdb mydiary;

script:
  - python -m pytest --cov-report term-missing --cov=app

  - cp .env.var .env

after_success:
  - coveralls
  - codeclimate

  