language: python
python:
  - "3.6"

install:
  - pip install -r requirements.txt

service:
  - postgresql

before_script:
  - createdb mydiary;

script:
  - cp .env.example .env.var
  - source .env.var
  - python -m pytest --cov-report term-missing --cov=app
  
after_success:
  - coveralls
  - codeclimate

  